/**
 * GrowthLoop Mock 数据
 *
 * 用于 Milestone 2 本地开发阶段，不接入 Supabase。
 * 数据设计参考 docs/PRD.md 数据对象定义。
 */

import type {
  Domain,
  Goal,
  Action,
  DailyLog,
  ActionRecord,
} from "@/types";

// ==================== 常量：用户 ID ====================
const USER_ID = "mock-user-001";

// ==================== 辅助：生成日期字符串 ====================
function dateStr(daysAgo: number): string {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString().split("T")[0]; // YYYY-MM-DD
}

const today = dateStr(0);
const yesterday = dateStr(1);
const twoDaysAgo = dateStr(2);

// ==================== 领域 ====================
export const domains: Domain[] = [
  {
    id: "dom-001",
    userId: USER_ID,
    name: "健康",
    description: "身体健康、心理健康、皮肤健康、社交关系健康",
    sortOrder: 1,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "dom-002",
    userId: USER_ID,
    name: "认知",
    description: "通用认知能力、思维模型、元认知",
    sortOrder: 2,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "dom-003",
    userId: USER_ID,
    name: "技能",
    description: "AI & Coding、摄影 & 后期、英语、唱歌 & 吉他",
    sortOrder: 3,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "dom-004",
    userId: USER_ID,
    name: "财务",
    description: "理财知识、储蓄目标、副业",
    sortOrder: 4,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
];

// ==================== 目标 ====================
export const goals: Goal[] = [
  {
    id: "goal-001",
    userId: USER_ID,
    domainId: "dom-003",
    parentGoalId: null,
    title: "完成 GrowthLoop v0.1 MVP",
    description:
      "独立完成 GrowthLoop 的最小闭环：目标 → 行动 → 记录 → 复盘 → 调整",
    horizon: "quarter",
    status: "active",
    isMainFocus: true,
    startDate: "2026-04-01",
    targetDate: "2026-06-30",
    createdAt: "2026-04-01T00:00:00Z",
    updatedAt: "2026-05-15T00:00:00Z",
  },
  {
    id: "goal-002",
    userId: USER_ID,
    domainId: "dom-001",
    parentGoalId: null,
    title: "每周运动 2 次",
    description: "保持基础体能，不追求高强度",
    horizon: "quarter",
    status: "active",
    isMainFocus: false,
    startDate: "2026-05-01",
    targetDate: "2026-08-01",
    createdAt: "2026-05-01T00:00:00Z",
    updatedAt: "2026-05-01T00:00:00Z",
  },
  {
    id: "goal-003",
    userId: USER_ID,
    domainId: "dom-003",
    parentGoalId: null,
    title: "每天英语最低行动",
    description: "保持英语语感，以最低行动保证连续性",
    horizon: "quarter",
    status: "active",
    isMainFocus: false,
    startDate: "2026-05-01",
    createdAt: "2026-05-01T00:00:00Z",
    updatedAt: "2026-05-01T00:00:00Z",
  },
];

// ==================== 行动 ====================
export const actions: Action[] = [
  {
    id: "act-001",
    userId: USER_ID,
    goalId: "goal-001",
    title: "完成类型定义和 Mock 数据",
    description: "创建 types/index.ts 和 lib/mock-data.ts",
    standardVersion: "完成所有类型定义 + 覆盖 4 领域、3 目标、5 行动",
    minimumVersion: "完成类型定义文件",
    frequency: "once",
    difficulty: "medium",
    isActive: true,
    isWeeklyFocus: true,
    createdAt: "2026-05-18T00:00:00Z",
    updatedAt: "2026-05-18T00:00:00Z",
  },
  {
    id: "act-002",
    userId: USER_ID,
    goalId: "goal-001",
    title: "实现 Dashboard 数据化",
    description: "把 Dashboard 从静态占位改为读取 mock 数据",
    standardVersion: "完成 Dashboard + Goals + Review 三页数据化",
    minimumVersion: "完成 Dashboard 单个页面数据化",
    frequency: "once",
    difficulty: "medium",
    isActive: true,
    isWeeklyFocus: true,
    createdAt: "2026-05-18T00:00:00Z",
    updatedAt: "2026-05-18T00:00:00Z",
  },
  {
    id: "act-003",
    userId: USER_ID,
    goalId: "goal-001",
    title: "编写统计函数",
    description: "创建 lib/stats.ts 实现基础统计",
    standardVersion: "实现 getTodayActions / getWeekCompletionRate / getRecentDailyLogs / getWeeklyReviewStats",
    minimumVersion: "实现 getTodayActions 和 getWeekCompletionRate",
    frequency: "once",
    difficulty: "easy",
    isActive: true,
    isWeeklyFocus: true,
    createdAt: "2026-05-18T00:00:00Z",
    updatedAt: "2026-05-18T00:00:00Z",
  },
  {
    id: "act-004",
    userId: USER_ID,
    goalId: "goal-002",
    title: "运动 30 分钟",
    description: "跑步或居家锻炼",
    standardVersion: "跑步 30 分钟或居家力量训练 30 分钟",
    minimumVersion: "散步 10 分钟",
    frequency: "weekly",
    difficulty: "medium",
    isActive: true,
    isWeeklyFocus: false,
    createdAt: "2026-05-01T00:00:00Z",
    updatedAt: "2026-05-01T00:00:00Z",
  },
  {
    id: "act-005",
    userId: USER_ID,
    goalId: "goal-003",
    title: "英语学习",
    description: "保持英语输入",
    standardVersion: "学习英语 45 分钟（阅读/听力/单词）",
    minimumVersion: "听 5 分钟英语播客或背 5 个单词",
    frequency: "daily",
    difficulty: "easy",
    isActive: true,
    isWeeklyFocus: false,
    createdAt: "2026-05-01T00:00:00Z",
    updatedAt: "2026-05-01T00:00:00Z",
  },
  {
    id: "act-006",
    userId: USER_ID,
    goalId: "goal-001",
    title: "代码 Review & 重构",
    description: "检查代码质量，保持项目整洁",
    standardVersion: "Review 全部本次变更文件 + 清理冗余代码",
    minimumVersion: "Review 1 个文件",
    frequency: "once",
    difficulty: "easy",
    isActive: true,
    isWeeklyFocus: false,
    createdAt: "2026-05-18T00:00:00Z",
    updatedAt: "2026-05-18T00:00:00Z",
  },
  {
    id: "act-007",
    userId: USER_ID,
    goalId: "goal-002",
    title: "睡眠管理",
    description: "保证充足睡眠",
    standardVersion: "23:00 前上床，保证 7.5 小时睡眠",
    minimumVersion: "00:00 前上床",
    frequency: "daily",
    difficulty: "medium",
    isActive: true,
    isWeeklyFocus: false,
    createdAt: "2026-05-01T00:00:00Z",
    updatedAt: "2026-05-01T00:00:00Z",
  },
];

// ==================== 每日记录 ====================
export const dailyLogs: DailyLog[] = [
  {
    id: "log-001",
    userId: USER_ID,
    date: twoDaysAgo,
    sleepHours: 6.5,
    energyScore: 3,
    moodScore: 3,
    stressScore: 4,
    note: "加了一天班，回家后只完成了最低行动版本。",
    blockers: "加班",
    createdAt: `${twoDaysAgo}T22:00:00Z`,
    updatedAt: `${twoDaysAgo}T22:00:00Z`,
  },
  {
    id: "log-002",
    userId: USER_ID,
    date: yesterday,
    sleepHours: 7,
    energyScore: 4,
    moodScore: 4,
    stressScore: 3,
    note: "状态还行，完成了两个核心行动。晚饭后有点累，但坚持写完了类型定义。",
    blockers: "",
    createdAt: `${yesterday}T22:30:00Z`,
    updatedAt: `${yesterday}T22:30:00Z`,
  },
  {
    id: "log-003",
    userId: USER_ID,
    date: today,
    sleepHours: 7.5,
    energyScore: 4,
    moodScore: 4,
    stressScore: 2,
    note: "今天精力不错，计划推进 Dashboard 数据化。",
    blockers: "",
    createdAt: `${today}T09:00:00Z`,
    updatedAt: `${today}T09:00:00Z`,
  },
];

// ==================== 行动完成记录 ====================
export const actionRecords: ActionRecord[] = [
  // -- 前天 --
  {
    id: "rec-001",
    userId: USER_ID,
    actionId: "act-003",
    dailyLogId: "log-001",
    date: twoDaysAgo,
    status: "minimum_done",
    note: "加班后只完成了两个核心统计函数",
    createdAt: `${twoDaysAgo}T22:00:00Z`,
    updatedAt: `${twoDaysAgo}T22:00:00Z`,
  },
  {
    id: "rec-002",
    userId: USER_ID,
    actionId: "act-005",
    dailyLogId: "log-001",
    date: twoDaysAgo,
    status: "minimum_done",
    note: "听了 5 分钟英语播客",
    createdAt: `${twoDaysAgo}T22:05:00Z`,
    updatedAt: `${twoDaysAgo}T22:05:00Z`,
  },
  {
    id: "rec-003",
    userId: USER_ID,
    actionId: "act-007",
    dailyLogId: "log-001",
    date: twoDaysAgo,
    status: "failed",
    note: "加班到很晚，00:30 才睡",
    createdAt: `${twoDaysAgo}T22:10:00Z`,
    updatedAt: `${twoDaysAgo}T22:10:00Z`,
  },
  // -- 昨天 --
  {
    id: "rec-004",
    userId: USER_ID,
    actionId: "act-001",
    dailyLogId: "log-002",
    date: yesterday,
    status: "done",
    note: "完成了类型定义和大部分 mock 数据",
    createdAt: `${yesterday}T22:30:00Z`,
    updatedAt: `${yesterday}T22:30:00Z`,
  },
  {
    id: "rec-005",
    userId: USER_ID,
    actionId: "act-003",
    dailyLogId: "log-002",
    date: yesterday,
    status: "done",
    note: "完成了 stats.ts 所有四个函数",
    createdAt: `${yesterday}T22:35:00Z`,
    updatedAt: `${yesterday}T22:35:00Z`,
  },
  {
    id: "rec-006",
    userId: USER_ID,
    actionId: "act-005",
    dailyLogId: "log-002",
    date: yesterday,
    status: "done",
    note: "学英语 30 分钟，阅读技术文章",
    createdAt: `${yesterday}T22:40:00Z`,
    updatedAt: `${yesterday}T22:40:00Z`,
  },
  {
    id: "rec-007",
    userId: USER_ID,
    actionId: "act-007",
    dailyLogId: "log-002",
    date: yesterday,
    status: "done",
    note: "23:15 上床",
    createdAt: `${yesterday}T22:45:00Z`,
    updatedAt: `${yesterday}T22:45:00Z`,
  },
  // -- 今天 --
  {
    id: "rec-008",
    userId: USER_ID,
    actionId: "act-002",
    dailyLogId: "log-003",
    date: today,
    status: "minimum_done",
    note: "正在推进 Dashboard 数据化",
    createdAt: `${today}T09:00:00Z`,
    updatedAt: `${today}T09:00:00Z`,
  },
  {
    id: "rec-009",
    userId: USER_ID,
    actionId: "act-005",
    dailyLogId: "log-003",
    date: today,
    status: "done",
    note: "早上学英语 45 分钟",
    createdAt: `${today}T09:05:00Z`,
    updatedAt: `${today}T09:05:00Z`,
  },
  {
    id: "rec-010",
    userId: USER_ID,
    actionId: "act-007",
    dailyLogId: "log-003",
    date: today,
    status: "done",
    note: "昨晚 23:00 上床，睡了 7.5 小时",
    createdAt: `${today}T09:10:00Z`,
    updatedAt: `${today}T09:10:00Z`,
  },
];